apiVersion: v1
kind: PersistentVolume
metadata:
  name: mini-proj-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/var/lib/jenkins/workspace/mini-proj/"
